name: PageSpeed Insights
on:
  deployment_status:

jobs:
  audit:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' && github.event.deployment.environment == 'Preview'
    steps:
      - name: Run PageSpeed Insights - Mobile
        uses: jakepartusch/psi-action@v1
        id: psi-mobile
        with:
          url: ${{ github.event.deployment_status.target_url }}
          threshold: 45
          strategy: mobile

      - name: Run PageSpeed Insights - Desktop
        uses: jakepartusch/psi-action@v1
        id: psi-desktop
        with:
          url: ${{ github.event.deployment_status.target_url }}
          threshold: 60
          strategy: desktop

      - name: Get PR number
        uses: jwalton/gh-find-current-pr@master
        id: pr

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ steps.pr.outputs.number }}
          comment-author: 'github-actions[bot]'
          body-includes: PageSpeed Insights Results

      - name: Comment PR
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v1
        if: steps.pr.outputs.number && success()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.pr.outputs.number }}
          body: |
            ### PageSpeed Insights Results

            ### Mobile
            Overall Score: ${{ steps.psi-mobile.outputs.score }}
            
            Performance: ${{ steps.psi-mobile.outputs.performance_score }}
            Accessibility: ${{ steps.psi-mobile.outputs.accessibility_score }}
            Best Practices: ${{ steps.psi-mobile.outputs.best_practices_score }}
            SEO: ${{ steps.psi-mobile.outputs.seo_score }}

            First Contentful Paint: ${{ steps.psi-mobile.outputs.first_contentful_paint }}
            Speed Index: ${{ steps.psi-mobile.outputs.speed_index }}
            Largest Contentful Paint: ${{ steps.psi-mobile.outputs.largest_contentful_paint }}
            Time to Interactive: ${{ steps.psi-mobile.outputs.interactive }}
            Total Blocking Time: ${{ steps.psi-mobile.outputs.total_blocking_time }}
            Cumulative Layout Shift: ${{ steps.psi-mobile.outputs.cumulative_layout_shift }}

            ### Desktop
            Overall Score: ${{ steps.psi-desktop.outputs.score }}
            
            Performance: ${{ steps.psi-desktop.outputs.performance_score }}
            Accessibility: ${{ steps.psi-desktop.outputs.accessibility_score }}
            Best Practices: ${{ steps.psi-desktop.outputs.best_practices_score }}
            SEO: ${{ steps.psi-desktop.outputs.seo_score }}

            First Contentful Paint: ${{ steps.psi-desktop.outputs.first_contentful_paint }}
            Speed Index: ${{ steps.psi-desktop.outputs.speed_index }}
            Largest Contentful Paint: ${{ steps.psi-desktop.outputs.largest_contentful_paint }}
            Time to Interactive: ${{ steps.psi-desktop.outputs.interactive }}
            Total Blocking Time: ${{ steps.psi-desktop.outputs.total_blocking_time }}
            Cumulative Layout Shift: ${{ steps.psi-desktop.outputs.cumulative_layout_shift }}

      - name: Update Comment PR
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        if: steps.pr.outputs.number && success()
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.pr.outputs.number }}
          body: |
            ### PageSpeed Insights Results

            ### Mobile
            Overall Score: ${{ steps.psi-mobile.outputs.score }}
            
            Performance: ${{ steps.psi-mobile.outputs.performance_score }}
            Accessibility: ${{ steps.psi-mobile.outputs.accessibility_score }}
            Best Practices: ${{ steps.psi-mobile.outputs.best_practices_score }}
            SEO: ${{ steps.psi-mobile.outputs.seo_score }}

            First Contentful Paint: ${{ steps.psi-mobile.outputs.first_contentful_paint }}
            Speed Index: ${{ steps.psi-mobile.outputs.speed_index }}
            Largest Contentful Paint: ${{ steps.psi-mobile.outputs.largest_contentful_paint }}
            Time to Interactive: ${{ steps.psi-mobile.outputs.interactive }}
            Total Blocking Time: ${{ steps.psi-mobile.outputs.total_blocking_time }}
            Cumulative Layout Shift: ${{ steps.psi-mobile.outputs.cumulative_layout_shift }}

            ### Desktop
            Overall Score: ${{ steps.psi-desktop.outputs.score }}
            
            Performance: ${{ steps.psi-desktop.outputs.performance_score }}
            Accessibility: ${{ steps.psi-desktop.outputs.accessibility_score }}
            Best Practices: ${{ steps.psi-desktop.outputs.best_practices_score }}
            SEO: ${{ steps.psi-desktop.outputs.seo_score }}

            First Contentful Paint: ${{ steps.psi-desktop.outputs.first_contentful_paint }}
            Speed Index: ${{ steps.psi-desktop.outputs.speed_index }}
            Largest Contentful Paint: ${{ steps.psi-desktop.outputs.largest_contentful_paint }}
            Time to Interactive: ${{ steps.psi-desktop.outputs.interactive }}
            Total Blocking Time: ${{ steps.psi-desktop.outputs.total_blocking_time }}
            Cumulative Layout Shift: ${{ steps.psi-desktop.outputs.cumulative_layout_shift }}